
services:
  # first-service:
  reminder-back:
    container_name: reminder-back
    # we can use build here to build the image from the Dockerfile or use a docker hub image
    build: . 
    volumes:
      # set a volume in the current directory 
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true=value
    depends_on:
      - reminder-db
    
  # first-service:

  reminder-db:
    container_name: reminder-db
    image: mongo:7.0.14
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-user
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      # set a volume in the current directory, if it doesn't exist it will be created
      - ./mongo:/data/db
      # :/data/db refers to the directory in the container where data will be stored, it changes depnding on the data base
    ports:
      - "27017:27017"

volumes:
  node_modules: